<?php

/**
 * @file
 * Contains axelerant.module
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Alters the existing Drupal "Site Information" form.
 */
function axelerant_form_system_site_information_settings_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Update text of the "Save configuration" button.
  $form['actions']['submit']['#value'] = t('Update Configuration');
}
